set_property SRC_FILE_INFO {cfile:E:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/constrs_1/new/board_xdc.xdc rfile:../../../led.srcs/constrs_1/new/board_xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {o_led[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {o_led[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports i_clk]
