set_property PACKAGE_PIN G17 [get_ports {o_led[0]}]
set_property PACKAGE_PIN G19 [get_ports {o_led[1]}]
set_property PACKAGE_PIN U18 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
