# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL.xci
# IP: The module: 'CLK_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL.xci
# IP: The module: 'CLK_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Qi_FPGA/prj/0.led/VIVADO18_Prj/led/led.srcs/sources_1/ip/CLK_PLL/CLK_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
